### PR TITLE
Update entities can be viewed by coordinates

### PR DESCRIPTION
**Pull request by LootSpace369**

### CODE REVIEW

**Comment by GameHerobrine** [comment]
*uh what would this thing be used to*

**Comment by GameHerobrine** [comment]
*or u meant to push it into scaxe*

**Comment by LootSpace369** [comment]
I think it's better at controlling the view and I'd at least like to incorporate the AI functions into Entity.php

**Comment by GameHerobrine** [comment]
- the function is protected which prevents from calling it anywhere(except Entity and child classes of it)
  - image
- the function does update yaw, but it doesnt seem to actually send it to clients(due to the way movement is sent in nc probably?)
- the code mixes tabs and spaces which should not be done(CONTRIBUTING.md)

**Pull request closed without merging**
