### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Estem01**

### CODE REVIEW

**Comment by kotyaralih** [comment]
why

**Comment by Estem01** [comment]
Lol 😂😂

**Comment by Estem01** [comment]
@kotyaralih Because it's not fork anymore I guess ._. there have already been several changes that you can tell that it is a modified version

**Comment by GameHerobrine** [comment]
fork and modified versions are pretty much the same thing

**Comment by Estem01** [comment]
@GameHerobrine So please disregard this pull request

**Comment by GameHerobrine** [comment]
sure i guess

**Pull request closed without merging**
